formatter: markdown table

settings:
  anchor: false
  escape: false
  indent: 4

output:
  file: ../../README.md
  mode: inject
  template: |-
    <!-- BEGIN_CLOUDTRAIL_DOCS -->
    {{ .Content }}
    <!-- END_CLOUDTRAIL_DOCS -->
